payout/urls.py
from django.urls import path
from . import views

app_name = 'payout'

urlpatterns = [
	path('', views.index, name='index'),
	path('departments', views.departments, name='departments'),
	path('department/<pk>', views.DepartmentUpdate.as_view(), name='updatedepartment'),
	path('workers', views.workers, name ='workers'),
	path('addworker', views.WorkerCreate.as_view(), name = 'addworker'),
	path('worker/<pk>', views.WorkerUpdate.as_view(), name ='updateworker'),
	path('newpayout', views.PayoutCreate.as_view(), name='newpayout'),
	path('report', views.report, name='report'),
	path('payout/<pk>', views.PayoutUpdate.as_view(), name = 'updatepayout'),
	path('weeklyreports', views.weeklyreports, name='weeklyreports'),
	path('advancedpayments', views.advancedpayments, name='advanced'),
	path('addadvancedpayment', views.Advanced_PaymentCreate.as_view(), name = 'addadvanced'),
	path('advancedpayment/<pk>', views.Advanced_PaymentUpdate.as_view(), name = 'updateadvanced'),
	path('tickets', views.tickets, name='tickets'),
	path('addticket', views.TicketCreate.as_view(), name = 'addticket'),
	path('ticketsummary', views.ticketsummary, name='ticketsummary'),
	path('updateticket/<pk>', views.TicketUpdate.as_view(), name = 'updateticket'),
	path('ticket/<pk>', views.ticket, name='viewticket'),
]

system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payout/', include('payout.urls')),
]

payout/models.py
from django import forms
from django.db import models
from datetime import date, timedelta
from django.urls import reverse
from django.db.models import Sum
from compositefk.fields import (
    CompositeForeignKey,
    RawFieldValue,
    LocalFieldValue,
    CompositeOneToOneField,
    FunctionBasedFieldValue,
)
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime
import string, random

# Create your models here.
class Department(models.Model):
	department_name = models.CharField(primary_key=True, max_length = 50)
	peso_multiplier = models.PositiveSmallIntegerField(default = 0)

	def get_absolute_url(self):
		return reverse('payout:departments')

	def __str__(self):
		return self.department_name

class Worker(models.Model):
	worker_name = models.CharField(max_length = 250)
	department_name = models.ForeignKey(Department, on_delete = models.DO_NOTHING, default = "None")
	accumulated_tickets = models.BigIntegerField( default = "0")
	accumulated_salary = models.FloatField( default = "0")
	last_date_paid = models.DateField(default = "1000-01-01")
	worker_type = models.CharField(max_length = 3, default = "REG")

	def get_absolute_url(self):
		return reverse('payout:workers')

	def __str__(self):
		# return str(self.pk) + ' ' + self.worker_name
		return self.worker_name

class Advanced_Payment(models.Model):
	worker_id = models.ForeignKey(Worker, on_delete = models.CASCADE)
	statuschoices = (("Pending", "Pending"), ("Done", "Done"))
	payment_status = models.CharField(max_length=10, choices = statuschoices, default = "Pending")
	date = models.DateField(default = "1000-01-01")

	class Meta:
		verbose_name ='Advanced Payment'
		verbose_name_plural = 'Advanced Payments'

	def get_absolute_url(self):
		return reverse('payout:advanced')

	def __str__(self):
		# return str(self.pk) + ' ' + self.worker_name
		return str(self.pk) + ' ' + str(self.worker_id)

class Payout(models.Model):
	date = models.DateField(default = "1000-01-01")
	number_of_tickets = models.PositiveSmallIntegerField(default = 0)
	amount_of_bonus = models.FloatField(default = 0.00)
	total_salary = models.FloatField(default = 0.00)
	worker = models.ForeignKey(Worker, on_delete = models.CASCADE)


	def save(self, *args, **kwargs):
		today = datetime.date.today()
		idx = (today.weekday()+1) % 7
		sun = today - datetime.timedelta(idx)
		sat = today + datetime.timedelta(6 - idx)

		self.date = sat
		self.total_salary = self.amount_of_bonus +(self.number_of_tickets*self.worker.department_name.peso_multiplier)#here is an error
		Worker.objects.filter(id = self.worker.id).update(last_date_paid = sat, accumulated_salary =+ self.total_salary, accumulated_tickets =+ self.number_of_tickets)

		super(Payout, self).save(*args, **kwargs)
		
		# if datetime.datetime.now() == sat:
		# 	if sat.hour() == 23:

		currweeklyreport = Weekly_Report.objects.filter(date=sat)
		if currweeklyreport.exists():
			print('Report already exists')
			print(sun)
			payouts = Payout.objects.filter(date__range=[sun,sat]).aggregate(Sum('total_salary'))
			# total = payouts
			print(payouts)
			total = payouts['total_salary__sum']
			# for payout in payouts:
			# 	total =+ payout['total_salary']
			currweeklyreport.update(weekly_total=total)
		else: 
			Weekly_Report().save()

	def get_absolute_url(self):
		return reverse('payout:report')

	def __str__(self):
		return str(self.pk)

class Weekly_Report(models.Model):
	date = models.DateField(default = "1000-01-01", primary_key = True)
	weekly_total = models.FloatField() 

	class Meta:
		verbose_name ='Weekly Report'
		verbose_name_plural = 'Weekly Reports'


	# if self.objects.filter(date=sat).exists():
	# if datetime.datetime.now() == sat:
	# 	if sat.hour() == 23:
	# 		print('Report already exists')
	# 	else: 
	# 		Weekly_Report.save()

	def save(self, *args, **kwargs):
		today = datetime.datetime.today()
		idx = (today.weekday()+1) % 7
		sun = today - datetime.timedelta(idx)
		sat = today + datetime.timedelta(6 - idx)
		self.date = sat
		payouts = Payout.objects.filter(date__range=[sun,sat]).values('total_salary')

		total = 0
		for payout in payouts:
			total =+ payout['total_salary']

		self.weekly_total = total

		super(Weekly_Report, self).save(*args, **kwargs)

	def __str__(self):
		return 'Week of ' + str(self.pk)

class Ticket(models.Model):
	style_name = models.CharField(default='style name', max_length=50)
	color = models.CharField(default='color', max_length=20)
	size1 = models.PositiveSmallIntegerField(verbose_name='35', default=0, validators=[MaxValueValidator(20), MinValueValidator(0)])
	size2= models.PositiveSmallIntegerField(verbose_name='36', default=0, validators=[MaxValueValidator(20), MinValueValidator(0)])
	size3 = models.PositiveSmallIntegerField(verbose_name='37', default=0, validators=[MaxValueValidator(20), MinValueValidator(0)])
	size4 = models.PositiveSmallIntegerField(verbose_name='38', default=0, validators=[MaxValueValidator(20), MinValueValidator(0)])
	size5 = models.PositiveSmallIntegerField(verbose_name='39', default=0, validators=[MaxValueValidator(20), MinValueValidator(0)])
	size6 = models.PositiveSmallIntegerField(verbose_name='40', default=0, validators=[MaxValueValidator(20), MinValueValidator(0)])

	no_pairs = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(20)])

	class Meta(object):
		unique_together = [("style_name","color")]

	def get_absolute_url(self):
		return reverse('payout:ticketsummary')

	def clean(self):
		if self.no_pairs > 20:
			raise form.ValidationError("Total number of pairs is above 20. You currently have " + self.no_pairs)

	def save(self, *args, **kwargs):

		self.no_pairs = self.size1 + self.size2 + self.size3 +  self.size4 + self.size5 + self.size6

		# self.full_clean()

		super(Ticket, self).save(*args, **kwargs)

payout/forms.py
# from django import forms
# from .models import Payout, Weekly_Report, Worker, Department

# class PayoutForm(forms.Form):
# 	worker = forms.ForeignKey(Worker, on_delete = CASCADE)
# 	number_of_tickets = models.PositiveSmallIntegerField()
# 	amount_of_bonus = models.FloatField()
# 	total_salary = models.FloatField()

from django.forms import ModelForm
from .models import Payout, Weekly_Report


class PayoutForm(ModelForm):
    class Meta:
        model = Payout
        fields = ['worker', 'number_of_tickets', 'amount_of_bonus', 'total_salary']


class ReportForm(ModelForm):
    class Meta:
        model = Weekly_Report
        fields = ['date', 'weekly_total']
        

payout/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Department, Worker, Payout, Weekly_Report, Advanced_Payment, Ticket
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, FormView
from .forms import PayoutForm, ReportForm
from datetime import date, timedelta
from django import forms
from django.core.exceptions import ValidationError
import datetime
# Create your views here.
def index(request):
	return render(request, 'payout/index.html')

def departments(request):
	departments = Department.objects.all()
	context = {
		'departments' : departments,
	}
	return render(request, 'payout/departments.html', context)

def workers(request):
	workers = Worker.objects.all()
	context = {
		'workers' : workers,
	}
	return render(request, 'payout/workers.html', context)

def report(request):

	today = datetime.date.today()
	idx = (today.weekday()+1) % 7
	sun = today - datetime.timedelta(idx)
	sat = today + datetime.timedelta(6 - idx)

	payouts = Payout.objects.filter(date=sat)

	context = {
		'payouts' : payouts,
		'sat': sat,
	}
	return render(request, 'payout/report.html', context)

def weeklyreports(request):

	reports = Weekly_Report.objects.all()
	context = {
		'reports': reports,
	}
	return render(request, 'payout/weeklyreports.html', context)

def advancedpayments(request):
	payments = Advanced_Payment.objects.filter(payment_status="Pending")
	context = {
		'payments' : payments,
	}
	return render(request, 'payout/advancedpayments.html', context)

def tickets(request):
	tickets = Ticket.objects.all()
	context = {
		'tickets': tickets,
	}
	return render(request, 'payout/tickets.html', context)

def workername_present(worker_name):
	if Worker.objects.filter(worker_name=worker_name).exists():
		return True
	return False

def ticketsummary(request):
	session_stylename = request.session.get('style_name')
	session_color = request.session.get('color')
	tickets = Ticket.objects.filter(style_name=session_stylename, color=session_color)
	# print (ticket)
	departments = Department.objects.all()
	context = {
		'tickets': tickets,
		'departments': departments,
	}
	return render(request, 'payout/ticketsummary.html', context)

def ticket(request, pk):
	# tickets = Ticket.objects.get(pk=pk)
	departments = Department.objects.all()
	ticket = get_object_or_404(Ticket, pk=pk)
	print (ticket)

	context = {
		'ticket' : ticket,
		'departments': departments,
	}
	return render(request, 'payout/ticket.html', context)

class WorkerCreate(CreateView):
	model = Worker
	fields = ['worker_name', 'department_name']

	def form_valid(self, form):
		if workername_present(self.request.POST.get('worker_name')) == True:
			form.add_error(None, ValidationError("Worker name is already taken"))
			return super().form_invalid(form)
		return super().form_valid(form)

class WorkerUpdate(UpdateView):
	model = Worker
	fields = ['worker_name','department_name']
	template_name='payout/update_worker.html'

class PayoutCreate(CreateView):
	model = Payout
	fields = ['worker', 'number_of_tickets', 'amount_of_bonus']

class PayoutUpdate(UpdateView):
	model = Payout
	fields = ['number_of_tickets','amount_of_bonus']
	template_name = 'payout/update_payout.html'

class DepartmentUpdate(UpdateView):
	model = Department
	fields = ['peso_multiplier']
	template_name = 'payout/update_pesomultiplier.html'

class Advanced_PaymentCreate(CreateView):
	model = Advanced_Payment
	fields = ['worker_id']
	template_name = 'payout/create_advanced.html'

class Advanced_PaymentUpdate(UpdateView):
	model = Advanced_Payment
	fields = ['payment_status']
	template_name = 'payout/update_advanced.html'

class TicketCreate(CreateView):
	model = Ticket
	fields = ['style_name','color', 'size1', 'size2', 'size3', 'size4', 'size5', 'size6']
	template_name = 'payout/create_ticket.html'

	def form_valid(self, form):
		# ticket = get_object_or_404(Ticket, id=self.kwargs['ticket'])
		# form.instance.no_pairs = ticket.no_pairs
		# self.object = self.get_object()
		size1 = int(self.request.POST.get('size1'))
		size2 = int(self.request.POST.get('size2'))
		size3 = int(self.request.POST.get('size3'))
		size4 = int(self.request.POST.get('size4'))
		size5 = int(self.request.POST.get('size5'))
		size6 = int(self.request.POST.get('size6'))
		total = size1 + size2 + size3 + size4 + size5 + size6

		if total > 20:
			form.add_error(None, ValidationError("Total number of pairs is above 20. You currently have " + str(total) +"."))
			return super().form_invalid(form)

		style_name_session = self.request.POST.get('style_name')
		color_session = self.request.POST.get('color')

		self.request.session['style_name'] = style_name_session
		self.request.session['color'] = color_session

		return super().form_valid(form)

class TicketUpdate(UpdateView):
	model = Ticket
	fields = ['style_name','color', 'size1', 'size2', 'size3', 'size4', 'size5', 'size6']
	template_name = 'payout/update_ticket.html'

	def form_valid(self, form):
		# ticket = get_object_or_404(Ticket, id=self.kwargs['ticket'])
		# form.instance.no_pairs = ticket.no_pairs
		# self.object = self.get_object()
		size1 = int(self.request.POST.get('size1'))
		size2 = int(self.request.POST.get('size2'))
		size3 = int(self.request.POST.get('size3'))
		size4 = int(self.request.POST.get('size4'))
		size5 = int(self.request.POST.get('size5'))
		size6 = int(self.request.POST.get('size6'))
		total = size1 + size2 + size3 + size4 + size5 + size6

		if total > 20:
			form.add_error(None, ValidationError("Total number of pairs is above 20. You currently have " + str(total) +"."))
			return super().form_invalid(form)

		style_name_session = self.request.POST.get('style_name')
		color_session = self.request.POST.get('color')

		self.request.session['style_name'] = style_name_session
		self.request.session['color'] = color_session

		return super().form_valid(form)


# def worker(request, worker_id):
# 	# worker = Worker.objects.get(pk=worker_id)
# 	worker = get_object_or_404(Worker, pk=worker_id)
# 	context = {
# 		'worker' : worker,
# 	}
# 	return render(request, 'payout/worker.html', context)

# class PayoutView(TemplateView):
# 	template_name = 'payout/payout_form.html'

# 	def get(self, request, *args, **kwargs):
# 	    payout_form = PayoutForm(self.request.GET or None)
# 	    report_form = ReportForm(self.request.GET or None)
# 	    context = self.get_context_data(**kwargs)
# 	    context['payout_form'] = payout_form
# 	    context['question_form'] = report_form
# 	    context['worker'] = Worker.objects.all()
# 	    context['payouts'] = Payout.objects.all()
# 	    return self.render_to_response(context)

# class PayoutFormView(FormView):
#     form_class = PayoutForm
#     template_name = 'payout/payout_form.html'
#     success_url = 'payout/report.html'

#     def post(self, request, *args, **kwargs):
# 	    payout_form = self.form_class(request.POST)
# 	    report_form = ReportForm()
# 	    if payout_form.is_valid():
# 	        payout_form.save()
# 	        return self.render_to_response(
# 	            self.get_context_data(
# 	            success=True
# 	        )
# 	    )
# 	    else:
# 	    	print ('not saved')
# 	    	return self.render_to_response(
# 		    	self.get_context_data(
# 		            payout_form=payout_form,
# 		        )
# 		    )

# class ReportFormView(FormView):
#     form_class = ReportForm
#     template_name = 'payout/payout_form.html'
#     success_url = 'payout/payout_form.html'

#     def post(self, request, *args, **kwargs):
#         report_form = self.form_class(request.POST)
#         payout_form = PayoutForm()
#         if report_form.is_valid():
#             report_form.save()
#             return self.render_to_response(
#                 self.get_context_data(
#                 success=True
#             )
#         )
#         else:
#             return self.render_to_response(
#             self.get_context_data(
#                     report_form=report_form,
#                     payout_form=payout_form
#             )
#         )

payout/templates/payout/advancedpayments.html
{% load static %}
  <!DOCTYPE html>
  <html>   
    <head>
      <!--Import Google Icon Font-->
      <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
      <!--Import materialize.css-->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/> -->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/stylesheet.css' %}"> -->

      <!--Let browser know website is optimized for mobile-->
      <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->
    </head>

    <body>
      <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
      <!-- <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script> -->

      {% include 'payout/nav.html' %}

      <h1> PINC SHOES PAYOUT SYSTEM </h1>
      <h2> Advanced Payments </h2>
      <p>
        <table>
          <tr>
            <th>Worker</th>
            <th>Last Date Paid</th>
            <th>Status</th>
          </tr>
          {% for payment in payments %}
          <tr>
            <td> {{payment.worker_id}} </td>
            <td> {{payment.worker_id.last_date_paid}} </td>
            <td> {{payment.get_payment_status_display}} </td>
            <td><button><a href="{% url 'payout:updateadvanced' payment.pk %}"> Update </a> </button> </td>
          </tr>
          {% endfor %}
        </table>
      </p>

      <div>
        <button><a href="{% url 'payout:index' %}"> Home</a> </button>
        <button><a href="{% url 'payout:addadvanced' %}"> Add worker </a> </button>
      </div>

    </body>
  </html>

payout/templates/payout/departments.html
  {% load static %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
      <!--Import materialize.css-->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/> -->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/stylesheet.css' %}"> -->

      <!--Let browser know website is optimized for mobile-->
      <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->
    </head>

    <body>
      <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
      <!-- <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script> -->

      {% include 'payout/nav.html' %}

      <h1> PINC SHOES PAYOUT SYSTEM </h1>
      <h2> Departments </h2>
      <p>
        <ul>
          {% for department in departments%}
            <li> <a href="{% url 'payout:updatedepartment' department.department_name %}">{{department.department_name}} </a></li>
          {% endfor %}
        </ul>
      </p>

      <div>
        <button><a href="{% url 'payout:index' %}"> Home</a> </button>
      </div>
    </body>
  </html>

payout/templates/payout/form-template.html
{% for field in form %}
	<div class ="form-group">
		<label>{{ field.label_tag }}</label>
		<div> {{field}} <div> 
	</div>
{% endfor %}

payout/templates/payout/report.html
{% load static %}
  <!DOCTYPE html>
  <html>   
    <head>
      <!--Import Google Icon Font-->
      <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
      <!--Import materialize.css-->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/> -->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/stylesheet.css' %}"> -->

      <!--Let browser know website is optimized for mobile-->
      <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->
    </head>

    <body>
      <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
      <!-- <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script> -->
      {% include 'payout/nav.html' %}
      
      <h1> PINC SHOES PAYOUT SYSTEM </h1>
      <h2> Payout - {{sat}} </h2>
      <p>
          <table>
            <tr>
              <th>Name</th>
              <th>Department</th>
              <th>Tickets</th>
              <th>Bonus</th>
              <th>Total</th>
              <th>Actions</th>
            </tr>
            {% for payout in payouts %}
            <tr>
              <td> {{payout.worker}} </td>
              <td> {{payout.worker.department_name}} </td>
              <td> {{payout.number_of_tickets}} </td>  
              <td> {{payout.amount_of_bonus}} </td>  
              <td> {{payout.total_salary}} </td>
              <td> <button><a href="{% url 'payout:updatepayout' payout.pk %}"> Update </a> </button> </td>
            </tr>
            {% endfor %}
          </table>

          <div>
            <button><a href="{% url 'payout:index' %}"> Home</a> </button>
            <button><a href="{% url 'payout:newpayout' %}"> Add Payout </a> </button>
          </div>
      </p>
    </body>
  </html>

payout/templates/payout/ticket.html
{% load static %}
  <!DOCTYPE html>
  <html>   
    <head>
      <!--Import Google Icon Font-->
      <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
      <!--Import materialize.css-->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/> -->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/stylesheet.css' %}"> -->

      <!--Let browser know website is optimized for mobile-->
      <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->
    </head>

    <body>
      <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
      <!-- <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script> -->

      {% include 'payout/nav.html' %}

      <h1> PINC SHOES PAYOUT SYSTEM </h1>
      <h2> Tickets </h2>
      <p>

        {% for department in departments %}
        <table>
          <tr>
            <th> Department </th>
            <th>Style Name</th>
            <th>Color</th>
            <th>Number of Pairs</th>
            <th>35</th>
            <th>36</th>
            <th>37</th>
            <th>38</th>
            <th>39</th>
            <th>40</th>
          </tr>
            <td>{{department.department_name}} </td>
            <td> {{ticket.style_name}} </td>
            <td> {{ticket.color}} </td>
            <td> {{ticket.no_pairs}} </td>
            <td> {{ticket.size1}} </td>
            <td> {{ticket.size2}} </td>
            <td> {{ticket.size3}} </td>
            <td> {{ticket.size4}} </td>
            <td> {{ticket.size5}} </td>
            <td> {{ticket.size6}} </td>
          </tr>
        </table>
        {% endfor %}
      </p>

      <div>
        <button><a href="{% url 'payout:tickets' %}"> Done </a> </button>

        <input type="button" value="Print Ticket" onclick="PrintMe()" />
        <script>
            function PrintMe(){
                window.print();
            }
        </script>
        
      </div>
    </body>
  </html>

payout/templates/payout/weeklyreports.html
{% load static %}
  <!DOCTYPE html>
  <html>   
    <head>
      <!--Import Google Icon Font-->
      <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
      <!--Import materialize.css-->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/> -->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/stylesheet.css' %}"> -->

      <!--Let browser know website is optimized for mobile-->
      <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->
    </head>

    <body>
      <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
      <!-- <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script> -->

      {% include 'payout/nav.html' %}

      <h1> PINC SHOES PAYOUT SYSTEM </h1>
      <h2> Weekly Reports </h2>
      <p>
        <table>
          <tr>
            <th>Date</th>
            <th>Total per Week</th>
          </tr>
          {% for report in reports %}
          <tr>
            <td> {{report.date}} </td>
            <td> {{report.weekly_total}} </td>
          </tr>
          {% endfor %}
        </table>
      </p>

      <div>
      <button><a href="{% url 'payout:index' %}"> Home</a> </button>
      </div>
    </body>
  </html>

payout/templates/payout/workers.html
{% load static %}
  <!DOCTYPE html>
  <html>   
    <head>
      <!--Import Google Icon Font-->
      <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
      <!--Import materialize.css-->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/> -->
      <!-- <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/stylesheet.css' %}"> -->

      <!--Let browser know website is optimized for mobile-->
      <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->
    </head>

    <body>
      <!--Import jQuery before materialize.js-->
      <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script> -->
      <!-- <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script> -->

      {% include 'payout/nav.html' %}

      <h1> PINC SHOES PAYOUT SYSTEM </h1>
      <h2> Workers </h2>
      <p>
        <table>
          <tr>
            <th>Name</th>
            <th>Department</th>
            <th>Accumulated Tickets</th>
            <th>Accumulated Salary</th>
            <th>Last Date Paid</th>
          </tr>
          {% for worker in workers%}
          <tr>
            <td> {{worker.worker_name}} </td>
            <td> {{worker.department_name}} </td>
            <td> {{worker.accumulated_tickets}} </td>
            <td> {{worker.accumulated_salary}} </td>
            <td> {{worker.last_date_paid}} </td>
            <td> <button><a href="{% url 'payout:updateworker' worker.pk%}"> Update </a> </button> </td>
          </tr>
          {% endfor %}
        </table>
      </p>

      <div>
        <button><a href="{% url 'payout:index' %}"> Home</a> </button>
        <button><a href="{% url 'payout:addworker' %}"> Add worker </a> </button>
      </div>
    </body>
  </html>